### ISSUE TITLE
Change folder structure to one subdirectory per test

### ISSUE THREAD

**Issue by johannes-wolf** [tingerrr/typst-test#2]
I propose changing the folder structure, such that each test file lives in its own folder. A test folder contains a Typst file (e.g. "test.typ") plus the reference image.

CeTZ currently uses its own test script, which structures the tests as given above, but we would like to use `typst-test`.

CeTZ's tests are recognized by recursively scanning the `tests/` directory for `test.typ` files and, if found, use the folder of those files as test-cases. This allows nesting/grouping tests by topic by just putting them in common parent directories.

**Comment by tingerrr** [comment]
That's a great idea, I was thinking about this too.

I was a little worried that it removes the simplicity of seeing all tests scripts in a single folder if they need no extra files.

I'll likely work on this next, as it reduces the amount of I/O-operations needed, which are a real hassle when it comes to error handling.
