### ISSUE TITLE
Error:unexpected character '\n' after patch version number

### ISSUE THREAD

**Issue by jneug** [tingerrr/typst-test#21]
I encountered the same issue as in #19.

When running a test, I get the message:
```
typst-test ran into an unexpected error, this is most likely a bug
Please consider reporting this at https://github.com/tingerrr/typst-test/issues/new
    Error:unexpected character '\n' after patch version number
```

Here is what I did:
```shell
cargo install typst-test --git https://github.com/tingerrr/typst-test
typst-test init
typst-test add test-1
typst-test run test1
```

The installation command gives the following warning:
```
   Compiling typst-test v0.1.0 (/Users/xxx/.cargo/git/checkouts/typst-test-af24935a6e1ceb4c/97b1839/crates/typst-test)
warning: variants `RootNotFound` and `InitNeeded` are never constructed
   --> crates/typst-test/src/project/mod.rs:398:5
    |
396 | pub enum Error {
    |          ----- variants in this enum
397 |     #[error("project not found: {0:?}")]
398 |     RootNotFound(PathBuf),
    |     ^^^^^^^^^^^^
...
404 |     InitNeeded,
    |     ^^^^^^^^^^
    |
    = note: `Error` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
    = note: `#[warn(dead_code)]` on by default

warning: `typst-test` (bin "typst-test") generated 1 warning
```

I ran the commands in several of my packages and even downloaded some other packages and always got the same error message.

I tried the `ci-semi-stabel` branch with no luck. The `ci-semi-stable` tag works for me, though.

**Comment by tingerrr** [comment]
The warnings are unrelated, they're there because those errors are not used in release mode, there are more checks in debug mode where they are used.

As stated in #19, I can't reproduce the issue, @keyneston, could you tell me if you're on macOS too? I'm testing on Linux, perhaps it is platform specific.

I don't know how this could happen though, this would imply that on macOS, somehow at the time `semver::Version::parse` is called, there's spurious newline at the end of its input.

**Comment by tingerrr** [comment]
It would be great if you could try running a debug version with `RUST_BACKTRACE=full`, because I can't really follow the error path through reasoning alone, it seems.

**Comment by jneug** [comment]
I get this:
```
           Stack backtrace:
              0: std::backtrace::Backtrace::create
              1: std::backtrace::Backtrace::capture
              2: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
              3: typst_test::util::command::parse_stdout
              4: typst_test::cmd::run_tests
              5: typst_test::cmd::run
              6: typst_test::main_impl
              7: typst_test::main
              8: std::sys_common::backtrace::__rust_begin_short_backtrace
              9: std::rt::lang_start::{{closure}}
             10: std::panicking::try
             11: std::rt::lang_start_internal
             12: _main
``

**Comment by jneug** [comment]
I dont know rust, but from looking through the code, code the problem be a call to `typst --version` to get the Typst version [here](https://github.com/tingerrr/typst-test/blob/4d8b0709822bcf6eaa4aa5575088513982a55d07/crates/typst-test-cli/src/main.rs#L526)? The output on my machine is
```
typst 0.11.1

```

There is a newline at the end. I think this is added by the Fish shell I'm using. Maybe trimming whitespace before parsing the version number would do the trick?

**Comment by tingerrr** [comment]
The stack trace explains it, I'll see to fixing it soon when I'm back home. Thanks!
