### ISSUE TITLE
Allow custom default tests

### ISSUE THREAD

**Issue by fenjalien** [tingerrr/typst-test#4]
Currently whenever a new test is created it is populated with "Hello World!". I then have to copy and paste in the package's import statement and other setup which is common to all tests I want to run.

I would like a way to change the default test on a per project basis.

**Comment by tingerrr** [comment]
Yeah, that sounds like a good feature to have. I think a `tests/template.typ` file will suffice for now, I don't want to rush into haphazard configuration before the `typst-manifest` crate is fully finished.

**Comment by tingerrr** [comment]
Implemented in ecbcd21259eb06ebdc7edca6216897a4d67c861b
